/**
 * Regenerates `example/theme.css` from a bundled `@marianmeres/design-tokens` theme,
 * using the `stuic-` prefix and the Bootstrap Reboot `--bs-*` bridge that
 * `example/reboot.css` consumes.
 *
 * Usage:
 *   deno task example:theme             # defaults to "zinc"
 *   deno task example:theme mauveTeal   # any bundled theme name
 *   deno task example:theme --list      # print available theme names
 *
 * The prefix and reboot bridge are mandatory — changing the prefix or dropping the
 * bridge breaks reboot.css. Only the palette is meant to vary here.
 */
import { generateThemedCss } from "@marianmeres/design-tokens/reboot";
import { bundledThemeNames, getBundledTheme } from "@marianmeres/design-tokens/themes";

const PREFIX = "stuic-";
const arg = Deno.args[0];

if (arg === "--list" || arg === "-l") {
	console.log(bundledThemeNames.join("\n"));
	Deno.exit(0);
}

const themeName = arg ?? "zinc";
const schema = getBundledTheme(themeName);

if (!schema) {
	console.error(
		`Unknown theme "${themeName}".\nAvailable: ${bundledThemeNames.join(", ")}`,
	);
	Deno.exit(1);
}

const header = `/*
 * Design tokens + Bootstrap Reboot bridge for the "${themeName}" theme.
 * Generated by @marianmeres/design-tokens — generateThemedCss(${themeName}, "${PREFIX}").
 * Light mode on :root, dark mode on :root.dark. Do not edit by hand;
 * regenerate with: deno task example:theme ${themeName}
 */
`;

const css = header + generateThemedCss(schema, PREFIX) + "\n";

await Deno.writeTextFile(new URL("../example/theme.css", import.meta.url), css);
console.log(`example theme → ${themeName} (prefix "${PREFIX}", with reboot bridge)`);
