/**
 * Writes the current package version into `example/src/version.generated.ts` so the
 * example can display it without reading `deno.json` at runtime. Run as the first step
 * of the `example:*` build tasks.
 */
import denoJson from "../deno.json" with { type: "json" };

const out = `// AUTO-GENERATED by scripts/gen-example-version.ts — do not edit.\n` +
	`export const VERSION = ${JSON.stringify(denoJson.version)};\n`;

await Deno.writeTextFile(
	new URL("../example/src/version.generated.ts", import.meta.url),
	out,
);
console.log(`example version → ${denoJson.version}`);
